import { VerticalBox } from "std-widgets.slint";
import { PluginParameter } from "parameter.slint";

export component ParameterKnob inherits Rectangle {
    in-out property <PluginParameter> parameter;
    in-out property <angle> min-angle: -250deg;
    in-out property <angle> max-angle:   70deg;
    in-out property <float> sensitivity: 0.25;

    in-out property <string> text;

    property <bool> changing;

    callback start-change();
    callback changed(float);
    callback end-change();
    callback set-string(string);

    horizontal-stretch: 0;
    vertical-stretch: 0;

    function start-editing() {
        edit-field.visible = true;
        edit-text-field.text = root.parameter.display-value;
        edit-text-field.focus();
        edit-text-field.select-all();
    }

    layout := VerticalLayout {
        alignment: center;
        spacing: 5px;

        texr := Rectangle {
            Text {
                text: " " + text + " ";
                color: white;
            }
        }

        // Knob area
        knob := Rectangle {
            height: 60px;
            width: 60px;
            border-radius: 200px;
            background: #3c230b;
            border-color: white;
            border-width: 6px;

            // Background arc
            Path {
                viewbox-x: -48;
                viewbox-y: -48;
                viewbox-width: 95;
                viewbox-height: 95;
                stroke: #3294f0;
                stroke-width: 8px;

                MoveTo {
                    x: Math.cos(root.min-angle) * 50;
                    y: Math.sin(root.min-angle) * 50;
                }

                ArcTo {
                    radius-x: 50;
                    radius-y: 50;
                    x: Math.cos(root.max-angle) * 50;
                    y: Math.sin(root.max-angle) * 50;
                    large-arc: true;
                    sweep: true;
                }
            }

            // Value arc
            if (root.max-angle - root.min-angle) * root.parameter.value <= 180deg: Path {
                viewbox-x: -50;
                viewbox-y: -50;
                viewbox-width: 100;
                viewbox-height: 100;
                stroke: touch.pressed ? #d9ff4f: touch.has-hover ? #001c99 : #2f2fef;
                stroke-width: 6px;

                MoveTo {
                    x: Math.cos(root.min-angle) * 48;
                    y: Math.sin(root.min-angle) * 48;
                }

                ArcTo {
                    radius-x: 48;
                    radius-y: 48;
                    x: Math.cos(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.value) * 48;
                    y: Math.sin(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.value) * 48;
                    sweep: true;
                }
            }

            if (root.max-angle - root.min-angle) * root.parameter.value > 180deg: Path {
                viewbox-x: -50;
                viewbox-y: -50;
                viewbox-width: 100;
                viewbox-height: 100;
                stroke: touch.pressed ? #d9ff4f: touch.has-hover ? #001c99 : #2f2fef;
                stroke-width: 6px;

                MoveTo {
                    x: Math.cos(root.min-angle) * 48;
                    y: Math.sin(root.min-angle) * 48;
                }

                ArcTo {
                    radius-x: 48;
                    radius-y: 48;
                    x: Math.cos(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.value) * 48;
                    y: Math.sin(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.value) * 48;
                    large-arc: true;
                    sweep: true;
                }    
            }

            // Modulation arc
            if (root.max-angle - root.min-angle) * (root.parameter.modulated-value - root.parameter.value) <= 180deg: Path {
                viewbox-x: -50;
                viewbox-y: -50;
                viewbox-width: 100;
                viewbox-height: 100;
                stroke: white.transparentize(50%);
                stroke-width: 6px;

                MoveTo {
                    x: Math.cos(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.value) * 48;
                    y: Math.sin(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.value) * 48;
                }

                ArcTo {
                    radius-x: 48;
                    radius-y: 48;
                    x: Math.cos(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.modulated-value) * 48;
                    y: Math.sin(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.modulated-value) * 48;
                    sweep: root.parameter.modulated-value > root.parameter.value;
                }
            }

            if (root.max-angle - root.min-angle) * (root.parameter.modulated-value - root.parameter.value) > 180deg: Path {
                viewbox-x: -50;
                viewbox-y: -50;
                viewbox-width: 100;
                viewbox-height: 100;
                stroke: white.transparentize(50%);
                stroke-width: 6px;

                MoveTo {
                    x: Math.cos(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.value) * 48;
                    y: Math.sin(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.value) * 48;
                }

                ArcTo {
                    radius-x: 48;
                    radius-y: 48;
                    x: Math.cos(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.modulated-value) * 48;
                    y: Math.sin(root.min-angle + (root.max-angle - root.min-angle) * root.parameter.modulated-value) * 48;
                    large-arc: true;
                    sweep: root.parameter.modulated-value > root.parameter.value;
                }    
            }

            touch := TouchArea {
                property <float> pressed-value;
        
                double-clicked => {
                    root.changed(root.parameter.default-value);
                }

                pointer-event(event) => {
                    if (event.button == PointerEventButton.left) {
                        if (event.kind == PointerEventKind.down) {
                            self.pressed-value = root.parameter.value;
                            root.start-change();
                            root.changing = true;
                
                            if (event.modifiers.control || event.modifiers.meta) {
                                start-editing();
                            }
                        } else if (event.kind == PointerEventKind.up || event.kind == PointerEventKind.cancel) {
                            root.end-change();
                            root.changing = false;
                        }
                    }
        
                    if (root.changing && event.kind == PointerEventKind.cancel) {
                        root.end-change();
                        root.changing = false;
                    }
                }
                moved => {
                    if (self.enabled && self.pressed) {
                        root.changed(clamp(self.pressed-value + (touch.pressed-y - touch.mouse-y) / root.height * root.sensitivity, 0.0, 1.0));
                    }
                }
            }
        }

        value-field := Rectangle {
            width: 60px;
            height: 15px;
            x: root.width / 2 - self.width / 2;
            background: white.transparentize(25%);
            border-radius: 10px;
    
            Text {
                text: root.parameter.display-value;
                font-size: 10px;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
    
            TouchArea {
                clicked => { start-editing(); }
            }
    
            edit-field := Rectangle {
                background: white;
                border-radius: 10px;
                visible: false;
    
                edit-text-field := TextInput {
                    font-size: 10px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    single-line: true;
    
                    accepted() => {
                        edit-field.visible = false;
                        root.set-string(self.text);
                    }
                }
            } 
        }
    }
}
